[package]
name = "corrector"
version = "0.1.0"
edition = "2021"

[lib]
name = "corrector"
path = "src/lib.rs"

[[bin]]
name = "corrector"
path = "src/main.rs"

[dependencies]
rayon = "1.5.3"
text_io = "0.1.12"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchy"
harness = false

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
